# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    #Python27:
    #  python.version: '2.7'
    #Python35:
    #  python.version: '3.5'
    Python36:
      python.version: '3.6'
    #Python368:
    #  python.version: '3.6.8'
    Python37:
      python.version: '3.7'

steps:
- script: |
    #working
    sudo apt-get update -y 
    sudo apt-get install -y mysql-server libmysqlclient-dev libcups2-dev python3 python3-pip python-dev python3-dev 
    #default-libmysqlclient-dev
    sudo apt-get install -y build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev  python-pip  
   
    #not sure if needed:
    ##sudo apt-get install libgirepository1.0-dev
    ##sudo apt install libcairo2-dev
    ##sudo apt-get install python3-cairo-dev
    ##sudo apt-get install libcairo2-dev
    

    ##sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev
    ##sudo apt-get install python3-cairo-dev
    ##sudo apt install libgirepository1.0-dev
    ##sudo apt install libgirepository1.0-dev libglib2.0-dev libcairo2-dev libffi-dev
    #needed:
    ##sudo apt-get install libgtk-3-dev
    
  displayName: 'Install sudo apt-get dependencies'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

#- script: |
#    pip install pytest pytest-azurepipelines
#    pytest
#  displayName: 'pytest'

